/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package readwithuslibmansystem;

/**
 *
 * @author abans tangalle
 */
public class LibrarianPanel extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianPanel
     */
    public LibrarianPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLliPa = new javax.swing.JLabel();
        btnRegMem = new javax.swing.JButton();
        btnSearBook = new javax.swing.JButton();
        btnChecReser = new javax.swing.JButton();
        btnBorro = new javax.swing.JButton();
        btnManBook = new javax.swing.JButton();
        btnManAuth = new javax.swing.JButton();
        btnViewBook = new javax.swing.JButton();
        btnFinePayment = new javax.swing.JButton();
        btnOverdue = new javax.swing.JButton();
        btnViewBorrow = new javax.swing.JButton();
        btnCreateAccount = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Librarian Panel");

        jPanel1.setLayout(null);

        jLliPa.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLliPa.setText("Librarian PANEL");
        jPanel1.add(jLliPa);
        jLliPa.setBounds(510, 20, 340, 60);

        btnRegMem.setBackground(new java.awt.Color(255, 255, 255));
        btnRegMem.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnRegMem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/memberregistrationneworig.png"))); // NOI18N
        btnRegMem.setText("Add Member");
        btnRegMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegMemActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegMem);
        btnRegMem.setBounds(30, 70, 420, 100);

        btnSearBook.setBackground(new java.awt.Color(255, 255, 255));
        btnSearBook.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnSearBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/searchbooknewori.png"))); // NOI18N
        btnSearBook.setText("Search Book");
        btnSearBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearBook);
        btnSearBook.setBounds(30, 330, 420, 100);

        btnChecReser.setBackground(new java.awt.Color(255, 255, 255));
        btnChecReser.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnChecReser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/reservebook2orig.png"))); // NOI18N
        btnChecReser.setText("Check Reserved Book");
        btnChecReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChecReserActionPerformed(evt);
            }
        });
        jPanel1.add(btnChecReser);
        btnChecReser.setBounds(470, 120, 420, 100);

        btnBorro.setBackground(new java.awt.Color(255, 255, 255));
        btnBorro.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnBorro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/borrowbooknewori.png"))); // NOI18N
        btnBorro.setText("Borrow Book");
        btnBorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorroActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorro);
        btnBorro.setBounds(30, 460, 420, 100);

        btnManBook.setBackground(new java.awt.Color(255, 255, 255));
        btnManBook.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnManBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/mangebooks.png"))); // NOI18N
        btnManBook.setText("Manage Book");
        btnManBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnManBook);
        btnManBook.setBounds(470, 400, 420, 100);

        btnManAuth.setBackground(new java.awt.Color(255, 255, 255));
        btnManAuth.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnManAuth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/manageauthor.jpg"))); // NOI18N
        btnManAuth.setText("Manage Author");
        btnManAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManAuthActionPerformed(evt);
            }
        });
        jPanel1.add(btnManAuth);
        btnManAuth.setBounds(470, 540, 420, 100);

        btnViewBook.setBackground(new java.awt.Color(255, 255, 255));
        btnViewBook.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnViewBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/viewbookori.png"))); // NOI18N
        btnViewBook.setText("View Book Details");
        btnViewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewBook);
        btnViewBook.setBounds(910, 330, 420, 100);

        btnFinePayment.setBackground(new java.awt.Color(255, 255, 255));
        btnFinePayment.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnFinePayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/finepayment2ori.png"))); // NOI18N
        btnFinePayment.setText("Fine Payment");
        btnFinePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinePaymentActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinePayment);
        btnFinePayment.setBounds(470, 260, 420, 100);

        btnOverdue.setBackground(new java.awt.Color(255, 255, 255));
        btnOverdue.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnOverdue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/overduebook.png"))); // NOI18N
        btnOverdue.setText("Check Overdue Books");
        btnOverdue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverdueActionPerformed(evt);
            }
        });
        jPanel1.add(btnOverdue);
        btnOverdue.setBounds(910, 70, 420, 100);

        btnViewBorrow.setBackground(new java.awt.Color(255, 255, 255));
        btnViewBorrow.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnViewBorrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/borrowbook3ori.png"))); // NOI18N
        btnViewBorrow.setText("ViewBorrowBooks");
        btnViewBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBorrowActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewBorrow);
        btnViewBorrow.setBounds(910, 200, 420, 100);

        btnCreateAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnCreateAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/Male-iconori.png"))); // NOI18N
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAccount);
        btnCreateAccount.setBounds(30, 200, 420, 100);

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/LOGOUTori.png"))); // NOI18N
        btnlogout.setText("Log Out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout);
        btnlogout.setBounds(910, 460, 420, 100);

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/backround6.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookActionPerformed
        ViewBook vb = new ViewBook();
        vb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewBookActionPerformed

    private void btnManAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManAuthActionPerformed
        ManageAuthor ma = new ManageAuthor();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManAuthActionPerformed

    private void btnManBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManBookActionPerformed
        ManageBook mb = new ManageBook();
        mb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManBookActionPerformed

    private void btnBorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorroActionPerformed
        BorrowBook bb = new BorrowBook();
        bb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBorroActionPerformed

    private void btnChecReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChecReserActionPerformed
        CheckReservedBook crb = new CheckReservedBook();
        crb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnChecReserActionPerformed

    private void btnSearBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearBookActionPerformed
        SearchBook sb = new SearchBook();
        sb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearBookActionPerformed

    private void btnRegMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegMemActionPerformed
        MemberRegistration mr = new MemberRegistration();
        mr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegMemActionPerformed

    private void btnFinePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinePaymentActionPerformed
        FinePaymentDetails fp = new FinePaymentDetails();
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFinePaymentActionPerformed

    private void btnOverdueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverdueActionPerformed
        OverDueBook od = new OverDueBook();
        od.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOverdueActionPerformed

    private void btnViewBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBorrowActionPerformed
        ViewBorrowBooks vb = new ViewBorrowBooks();
        vb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewBorrowActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        Librarian l = new Librarian();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        Login mp = new Login();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorro;
    private javax.swing.JButton btnChecReser;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnFinePayment;
    private javax.swing.JButton btnManAuth;
    private javax.swing.JButton btnManBook;
    private javax.swing.JButton btnOverdue;
    private javax.swing.JButton btnRegMem;
    private javax.swing.JButton btnSearBook;
    private javax.swing.JButton btnViewBook;
    private javax.swing.JButton btnViewBorrow;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLliPa;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
