/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package readwithuslibmansystem;

/**
 *
 * @author abans tangalle
 */
public class MemberPanel extends javax.swing.JFrame {

    /**
     * Creates new form StudentPanel
     */
    public MemberPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnReser = new javax.swing.JButton();
        btnSearc = new javax.swing.JButton();
        btnViewBoo = new javax.swing.JButton();
        btnChOverdue = new javax.swing.JButton();
        btnviewborrow = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Member Panel");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setText("MEMBER PANEL");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(540, 30, 310, 70);

        btnReser.setBackground(new java.awt.Color(255, 255, 255));
        btnReser.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnReser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/reservebook2orig.png"))); // NOI18N
        btnReser.setText("Reserve Book");
        btnReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserActionPerformed(evt);
            }
        });
        jPanel1.add(btnReser);
        btnReser.setBounds(200, 330, 420, 100);

        btnSearc.setBackground(new java.awt.Color(255, 255, 255));
        btnSearc.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnSearc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/searchbooknewori.png"))); // NOI18N
        btnSearc.setText("Search Books");
        btnSearc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearcActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearc);
        btnSearc.setBounds(200, 150, 420, 100);

        btnViewBoo.setBackground(new java.awt.Color(255, 255, 255));
        btnViewBoo.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnViewBoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/viewbookori.png"))); // NOI18N
        btnViewBoo.setText("View Book Details");
        btnViewBoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBooActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewBoo);
        btnViewBoo.setBounds(740, 150, 420, 100);

        btnChOverdue.setBackground(new java.awt.Color(255, 255, 255));
        btnChOverdue.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnChOverdue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/overduebook.png"))); // NOI18N
        btnChOverdue.setText("Check Overdue Books");
        btnChOverdue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChOverdueActionPerformed(evt);
            }
        });
        jPanel1.add(btnChOverdue);
        btnChOverdue.setBounds(740, 330, 420, 100);

        btnviewborrow.setBackground(new java.awt.Color(255, 255, 255));
        btnviewborrow.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnviewborrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/borrowbook3ori.png"))); // NOI18N
        btnviewborrow.setText("View Borrow Details");
        btnviewborrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewborrowActionPerformed(evt);
            }
        });
        jPanel1.add(btnviewborrow);
        btnviewborrow.setBounds(740, 500, 420, 100);

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/LOGOUTori.png"))); // NOI18N
        btnLogOut.setText("LOGOUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(200, 500, 420, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMSImages/backround6.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1500, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewBooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBooActionPerformed
        ViewBook vbd = new ViewBook();
        vbd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewBooActionPerformed

    private void btnSearcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearcActionPerformed
        SearchBook sb = new SearchBook();
        sb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearcActionPerformed

    private void btnReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserActionPerformed
        ReserveBook rb = new ReserveBook();
        rb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReserActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        Login mp = new Login();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnChOverdueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChOverdueActionPerformed
        OverDueBook od = new OverDueBook();
        od.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnChOverdueActionPerformed

    private void btnviewborrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewborrowActionPerformed
        ViewBorrowBooks vbb = new ViewBorrowBooks();
        vbb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnviewborrowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChOverdue;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReser;
    private javax.swing.JButton btnSearc;
    private javax.swing.JButton btnViewBoo;
    private javax.swing.JButton btnviewborrow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
